meta:
  engine: 4.1.0
  
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy

  # Padding Variables
  px: kx + 2
  py: ky + 2

  # extra padding for case.
  dpx: kx + 8
  dpy: ky + 8

  # case wall width = dp(x/y) - p(x/y)

  screw_size: 1.85
  standoff_size: 3 # screw outer radius

  $default_width: cx
  $default_height: cy

points:
  zones:
    matrix:
      key:
        padding: 1ky + 0.75
        spread: 1kx + 0.75
      anchor:
        shift: [100, -100]
      columns:
        # left to right
        outer:
          key.column_net: P1
        pinky:
          key.column_net: P0
        ring:
          key:
            stagger: 0.3kx
            column_net: P2
        middle:
          key:
            stagger: 0.3kx
            column_net: P3
        index:
          key:
            stagger: -0.3kx
            column_net: P4
        inner:
          key.column_net: P5
      rows:
        # bottom to top
        bottom:
          row_net: P19
        home:
          row_net: P20
        top:
          row_net: P21
    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-1.5kx, -ky - 5]
      key:
        padding: 1ky + 0.75
        spread: 1kx + 0.75
      columns:
        one:
          key:
            splay: -10
            column_net: P2
        two:
          key:
            splay: -9
            shift: [3, -1] 
            column_net: P3
        three:
          key:
            splay: -8
            shift: [6, -2]
            column_net: P4
        four:
          key:
            splay: -10
            shift: [9, -2]
            column_net: P5
      rows:
        cluster:
          row_net: P10

outlines:
  board_left: # we do not have a right board, we only use this and reversi it for the right board
    - what: polygon
      fillet: 2
      operation: stack
      points:
        # top part
        - ref: matrix_outer_top
          shift: [-0.55px, 0.55py]
        - ref: matrix_outer_top
          shift: [0.55px, 0.55py]
        - ref: matrix_pinky_top
          shift: [0.55px - 3, 0.55py]
        - ref: matrix_ring_top
          shift: [-0.55px, 0.55py]
        - ref: matrix_ring_top
          shift: [0.55px - 3, 0.55py]
        - ref: matrix_middle_top
          shift: [-0.55px, 0.55py]
        - ref: matrix_middle_top
          shift: [0.55px, 0.55py]
        - ref: matrix_index_top
          shift: [-0.55px + 3, 0.55py]
        - ref: matrix_inner_top
          shift: [1.7px, 0.55py]

        # bottom part
        - ref: thumbs_four_cluster
          shift: [-0.35px, 0.55py + 1]
        - ref: thumbs_four_cluster
          shift: [0.55px, 0.55py]
        - ref: thumbs_four_cluster
          shift: [0.55px, -0.55py]
        - ref: thumbs_three_cluster
          shift: [0.55px, -0.55py]
        - ref: thumbs_three_cluster
          shift: [-0.55px, -0.55py]
        - ref: thumbs_one_cluster
          shift: [0.55px, -0.55py]
        - ref: thumbs_one_cluster
          shift: [-0.55px, -0.55py]
        - ref: matrix_pinky_bottom
          shift: [0.55px, -0.55py]
        - ref: matrix_outer_bottom
          shift: [-0.55px, -0.55py]

  # big board for case
  xl_board_left:
    - what: polygon
      fillet: 2
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_outer_top
          shift: [0.5dpx, 0.5dpy]
        - ref: matrix_pinky_top
          shift: [0.5dpx - 7, 0.5dpy]
        - ref: matrix_ring_top
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_ring_top
          shift: [0.5dpx - 7, 0.5dpy]
        - ref: matrix_middle_top
          shift: [-0.5dpx, 0.5dpy]
        - ref: matrix_middle_top
          shift: [0.5dpx, 0.5dpy]
        - ref: matrix_index_top
          shift: [-0.5dpx + 7, 0.5dpy]
        - ref: matrix_inner_top
          shift: [1.8px, 0.5dpy]

        - ref: thumbs_four_cluster
          shift: [-0.2dpx, 0.5dpy + 1]
        - ref: thumbs_four_cluster
          shift: [0.5dpx, 0.5dpy]
        - ref: thumbs_four_cluster
          shift: [0.5dpx, -0.5dpy]
        - ref: thumbs_three_cluster
          shift: [0.5dpx, -0.55dpy]
        - ref: thumbs_three_cluster
          shift: [-0.5dpx, -0.55dpy]
        - ref: thumbs_one_cluster
          shift: [0.5dpx, -0.55dpy]
        - ref: thumbs_one_cluster
          shift: [-0.5dpx, -0.5dpy]
        - ref: matrix_pinky_bottom
          shift: [0.4dpx, -0.5dpy]
        - ref: matrix_outer_bottom
          shift: [-0.5dpx, -0.5dpy]

  top: # for top case
    - what: polygon
      fillet: 2
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.55px, 0.55py]
        - ref: matrix_outer_top
          shift: [0.55px, 0.55py]
        - ref: matrix_pinky_top
          shift: [0.55px - 3, 0.55py]
        - ref: matrix_ring_top
          shift: [-0.55px, 0.55py]
        - ref: matrix_ring_top
          shift: [0.55px - 3, 0.55py]
        - ref: matrix_middle_top
          shift: [-0.55px, 0.55py]
        - ref: matrix_middle_top
          shift: [0.55px, 0.55py]
        - ref: matrix_index_top
          shift: [-0.55px + 3, 0.55py]
        - ref: matrix_inner_top
          shift: [0.55px + 1, 0.55py]
        - ref: matrix_inner_home
          shift: [0.55px + 1, -1.55py + 1]
        - ref: matrix_inner_home
          shift: [1.5px + 3.7, -1.55py + 1]

        - ref: thumbs_four_cluster
          shift: [-0.35px, 0.55py + 1]
        - ref: thumbs_four_cluster
          shift: [0.55px, 0.55py]
        - ref: thumbs_four_cluster
          shift: [0.55px, -0.55py]
        - ref: thumbs_three_cluster
          shift: [0.55px, -0.55py]
        - ref: thumbs_three_cluster
          shift: [-0.55px, -0.55py]
        - ref: thumbs_one_cluster
          shift: [0.55px, -0.55py]
        - ref: thumbs_one_cluster
          shift: [-0.55px, -0.55py]
        - ref: matrix_pinky_bottom
          shift: [0.55px, -0.55py]
        - ref: matrix_outer_bottom
          shift: [-0.55px, -0.55py]

  mounting: # mounting screw inner
    - what: circle
      radius: screw_size
      where: 
        ref: matrix_outer_top
        shift: [0.45px, 5]
    - what: circle
      radius: screw_size
      where: 
        ref: matrix_ring_bottom
        shift: [0.45px, -1px]
    - what: circle
      radius: screw_size
      where: 
        ref: matrix_inner_top
        shift: [0.5px, 0.2px]
    - what: circle
      radius: screw_size
      where: 
        ref: thumbs_three_cluster
        shift: [0, 0.8px]
    - what: circle
      radius: screw_size
      where: 
        ref: matrix_ring_home
        shift: [0.45px, 0.4px]

  mounting_top_case: # the top will be mounted by only 2 screws, just to keep it in place
    - what: circle
      radius: screw_size
      where: 
        ref: matrix_ring_bottom
        shift: [0.45px, -1px]
    - what: circle
      radius: screw_size
      where: 
        ref: thumbs_three_cluster
        shift: [0, 0.8px]

  standoff: # mounting screw outer
    - what: circle
      radius: standoff_size
      where: 
        ref: matrix_outer_top
        shift: [0.45px, 5]
    - what: circle
      radius: standoff_size
      where: 
        ref: matrix_ring_bottom
        shift: [0.45px, -1px]
    - what: circle
      radius: standoff_size
      where: 
        ref: matrix_inner_top
        shift: [0.5px, 0.2px]
    - what: circle
      radius: standoff_size
      where: 
        ref: thumbs_three_cluster
        shift: [0, 0.8px]
    - what: circle
      radius: standoff_size
      where: 
        ref: matrix_ring_home
        shift: [0.45px, 0.4px]

  standoff_top_case:
    - what: circle
      radius: standoff_size
      where: 
        ref: matrix_ring_bottom
        shift: [0.45px, -1px]
    - what: circle
      radius: standoff_size
      where: 
        ref: thumbs_three_cluster
        shift: [0, 0.8px]

  keys:
    - what: rectangle
      where: true
      size: [16, 16]

pcbs:
  board:
    template: kicad8
    outlines:
      main:
        outline: board_left
    footprints:
      choc:
        what: choc
        where: /^matrix_.*|^thumbs_.*/
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode:
        what: diode
        where: /^matrix_.*|^thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, 5]
      supermini:
        what: supermini
        params:
          reversible: true
        where:
          ref: matrix_inner_top
          shift: [1.1px, -0.4px]
          rotate: 0
      battery_jack:
        what: jstph
        where:
          ref: matrix_inner_bottom
          shift: [1px + 2, -px + 10.0]
          rotate: 180
        params:
            side: B
            pos: pos
            neg: GND
      power_slider:
        what: slider
        where:
            ref: matrix_inner_bottom
            shift: [1.5px + 2, 5.0]
            rotate: -90
        params:
            side: F
            from: pos
            to: RAW
      reset_button:
        what: EVQPUC
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: matrix_inner_bottom
          shift: [1.5px + 2, -4]
          rotate: -90
      mounting_hole_nw:
        what: mountinghole
        where: 
          ref: matrix_outer_top
          shift: [0.45px, 5]
      mounting_hole_sw:
        what: mountinghole
        where: 
          ref: matrix_ring_bottom
          shift: [0.45px, -1px]
      mounting_hole_ne:
        what: mountinghole
        where: 
          ref: matrix_inner_top
          shift: [0.5px, 0.2px]
      mounting_hole_se:
        what: mountinghole
        where: 
          ref: thumbs_three_cluster
          shift: [0, 0.8px]
      mounting_hole_mid:
        what: mountinghole
        where: 
          ref: matrix_ring_home
          shift: [0.45px, 0.4px]

cases:
  # flat bottom
  _bottom:
    - name: board_left
      extrude: 1.2
  _xl_bottom:
    - name: xl_board_left
      extrude: 1.2

  _top:
    - name: top
      extrude: 1.2

  _outer_wall:
    - name: xl_board_left
      extrude: 10
  _inner_wall:
    - name: board_left
      extrude: 10
  _wall:
    - what: case
      name: _outer_wall
      operation: add
    - what: case
      name: _inner_wall
      operation: subtract

  _outer_wall_open:
    - name: xl_board_left
      extrude: 5.6
  _inner_wall_open:
    - name: board_left
      extrude: 5.6
  _wall_open:
    - what: case
      name: _outer_wall_open
      operation: add
    - what: case
      name: _inner_wall_open
      operation: subtract

  # cutout for the keys
  _keys_cutout:
    - name: keys
      extrude: 1.2

  # holes for the screws
  _holes:
    - name: mounting
      extrude: 8.4
  _standoffs:
    - name: standoff
      extrude: 8.4

  _holes_top:
    - name: mounting_top_case
      extrude: 1.2
  _standoffs_top:
    - name: standoff_top_case
      extrude: 1.2

  _holes_open:
    - name: mounting
      extrude: 4
  _standoffs_open:
    - name: standoff
      extrude: 4

  top_case:
    - what: case
      name: _top
      operation: add
    - what: case
      name: _keys_cutout
      operation: subtract

    - what: case
      name: _standoffs_top
      operation: add
    - what: case
      name: _holes_top
      operation: subtract

  bottom_case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract

    - what: case
      name: _xl_bottom
      operation: add
    - what: case
      name: _wall
      operation: add

  open_case:
    - what: case
      name: _standoffs_open
      operation: add
    - what: case
      name: _holes_open
      operation: subtract

    - what: case
      name: _xl_bottom
      operation: add
    - what: case
      name: _wall_open
      operation: add
