meta:
  engine: 4.1.0
  
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2

  $default_width: cx
  $default_height: cy

points:
  zones:
    matrix:
      key:
        padding: 1ky + 0.75
        spread: 1kx + 0.75
      anchor:
        shift: [100, -100]
      columns:
        # left to right
        outer:
        pinky:
        ring:
          key.stagger: 0.7kx
        middle:
          key.stagger: 0.5kx
        index:
          key.stagger: -0.38kx
        inner:
      rows:
        # bottom to top
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-1.5kx, -ky - 5]
      key:
        padding: 1ky + 0.75
        spread: 1kx + 0.75
      columns:
        one:
          key.splay: -10
        two:
          key:
            splay: -9
            shift: [3, -1] 
        three:
          key:
            splay: -8
            shift: [6, -2]
        four:
          key:
            splay: -10
            shift: [9, -2]
      rows:
        cluster:
  
  mirror:
    ref: thumbs_four_cluster
    distance: 2kx

outlines:
  board_left:
    - what: polygon
      fillet: 2
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-px / 2, py / 2]
        - ref: matrix_outer_top
          shift: [px / 2, py / 2]
        - ref: matrix_pinky_top
          shift: [px / 2 - 1, py / 2]
        - ref: matrix_ring_top
          shift: [-px / 2, py / 2]
        - ref: matrix_ring_top
          shift: [px / 2 - 1, py / 2]
        - ref: matrix_middle_top
          shift: [-px / 2, py / 2]
        - ref: matrix_middle_top
          shift: [px / 2, py / 2]
        - ref: matrix_index_top
          shift: [-px / 2 + 1, py / 2]
        - ref: matrix_inner_top
          shift: [px / 2, py / 2]
        - ref: matrix_inner_bottom
          shift: [px / 2, -py / 2]

        - ref: thumbs_three_cluster
          shift: [-px / 2, py / 2 + 1]
        - ref: thumbs_four_cluster
          shift: [-px / 2, py / 2 + 1]
        - ref: thumbs_four_cluster
          shift: [px / 2, py / 2]
        - ref: thumbs_four_cluster
          shift: [px / 2, -py / 2]
        - ref: thumbs_three_cluster
          shift: [px / 2, -py / 2]
        - ref: thumbs_three_cluster
          shift: [-px / 2, -py / 2]
        - ref: thumbs_one_cluster
          shift: [px / 2, -py / 2]
        - ref: thumbs_one_cluster
          shift: [-px / 2, -py / 2]
        - ref: matrix_pinky_bottom
          shift: [px / 2, -py / 2]
        - ref: matrix_outer_bottom
          shift: [-px / 2, -py / 2]

  board_right:
    - what: polygon
      fillet: 2
      operation: stack
      points:
        - ref: mirror_matrix_outer_top
          shift: [-px / 2, py / 2]
        - ref: mirror_matrix_outer_top
          shift: [px / 2, py / 2]
        - ref: mirror_matrix_pinky_top
          shift: [px / 2 - 1, py / 2]
        - ref: mirror_matrix_ring_top
          shift: [-px / 2, py / 2]
        - ref: mirror_matrix_ring_top
          shift: [px / 2 - 1, py / 2]
        - ref: mirror_matrix_middle_top
          shift: [-px / 2, py / 2]
        - ref: mirror_matrix_middle_top
          shift: [px / 2, py / 2]
        - ref: mirror_matrix_index_top
          shift: [-px / 2 + 1, py / 2]
        - ref: mirror_matrix_inner_top
          shift: [px / 2, py / 2]
        - ref: mirror_matrix_inner_bottom
          shift: [px / 2, -py / 2]

        - ref: mirror_thumbs_three_cluster
          shift: [-px / 2, py / 2 + 1]
        - ref: mirror_thumbs_four_cluster
          shift: [-px / 2, py / 2 + 1]
        - ref: mirror_thumbs_four_cluster
          shift: [px / 2, py / 2]
        - ref: mirror_thumbs_four_cluster
          shift: [px / 2, -py / 2]
        - ref: mirror_thumbs_three_cluster
          shift: [px / 2, -py / 2]
        - ref: mirror_thumbs_three_cluster
          shift: [-px / 2, -py / 2]
        - ref: mirror_thumbs_one_cluster
          shift: [px / 2, -py / 2]
        - ref: mirror_thumbs_one_cluster
          shift: [-px / 2, -py / 2]
        - ref: mirror_matrix_pinky_bottom
          shift: [px / 2, -py / 2]
        - ref: mirror_matrix_outer_bottom
          shift: [-px / 2, -py / 2]

pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^matrix_.*|^thumbs_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode_main:
        what: diode
        where: /^matrix_.*|^thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      seeed_xiao:
        what: seeed_xiao
        where:
          ref: matrix_inner_top
          shift: [20, 20]
          rotate: 0
      reset:
        what: button
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror_matrix_.*|^mirror_thumbs_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode_main:
        what: diode
        where: /^mirror_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
